### ISSUE TITLE
reward sound on windows

### ISSUE THREAD

**Issue by smh020** [sarajaksa/anki-addons#1]
I'm having difficulty getting your addon to work for windows. Could you show an example of how you would refer to the audio folder?

**Comment by sarajaksa** [comment]
For example, I have my music in my Dropbox folder on the separate disk partition. So I changed the 15 line to:

    audioPath = ["E:\Dropbox\Music"]

I guess if you keep it in your Document folder, it might be something like

    audioPath = ["C:\Users\<user>\Documents\<name of the folder>"]

It is important to put the absolute folder path inside the parenthesis. In Windows 7, I am able to see the absolute path in the title bar and I can copy it by clicking on the address line. Not sure how it is done on other versions of Windows.
